language: node_js

node_js:
  - 20

env:
  - SCRIPTS=$TRAVIS_BUILD_DIR/.travis

cache:
  npm: true

services:
  - docker

before_script:
  - echo -e "Host $PRODUCTION_SERVER_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

before_install:
  - curl -fsSL https://bun.sh/install | bash
  - source ~/.bashrc
  - bun --version

install:
  - bun install
  - npx playwright install
  - npx playwright install-deps

jobs:
  include:
    - stage: Test
      name: "Run Unit Tests"
      script: bun run test:prod

    - stage: Code Linting
      if: type = pull_request
      script:
        - bun run lint

    - stage: Deploy Backend Image
      if: type != pull_request
      script:
        - $SCRIPTS/add_ssh_key
        - $SCRIPTS/build_image
        - $SCRIPTS/deploy_image
        - $SCRIPTS/start_container
