language: node_js

script: 'true'

node_js:
  - 20

env:
  - SCRIPTS=$TRAVIS_BUILD_DIR/.travis
  - WEB_TIMEOUT=360

cache:
  npm: true

services:
  - docker

before_script:
  - echo -e "Host $PRODUCTION_SERVER_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

before_install:
  - curl -fsSL https://bun.sh/install | bash
  - source ~/.bashrc
  - bun --version
  - openssl aes-256-cbc -K $encrypted_1d0be07602a8_key -iv $encrypted_1d0be07602a8_iv -in ./.travis/travis-cert.pem.enc -out ./.travis/dev_cert.pem -d
  - openssl aes-256-cbc -K $encrypted_cd0b29a82eff_key -iv $encrypted_cd0b29a82eff_iv -in ./.travis/production_cert.pem.enc -out ./.travis/production_cert.pem -d

install:
  - bun install

jobs:
  include:
    - stage: Code Linting
      if: type = pull_request
      script:
        - bun run lint
    - stage: Run Development Tests
      if: branch != main AND type != pull_request
      script:
        - npx playwright install
        - npx playwright install-deps > /dev/null
        - bun run test

    - stage: Run Production Tests
      if: type = pull_request
      script:
        - npx playwright install
        - npx playwright install-deps > /dev/null
        - bun run test:prod

    - stage: Deploy Backend Image
      if: type != pull_request
      script:
        - $SCRIPTS/add_ssh_key
        - $SCRIPTS/build_image
        - $SCRIPTS/deploy_image
        - $SCRIPTS/start_container
