dist: jammy

language: node
node_js:
  - 20

script: 'true'

env:
  global:
    - SCRIPTS=$TRAVIS_BUILD_DIR/.travis
    - WEB_TIMEOUT=360

services:
  - docker

before_script:
  - echo -e "Host $PRODUCTION_SERVER_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_1d0be07602a8_key -iv $encrypted_1d0be07602a8_iv -in ./.travis/travis-cert.pem.enc -out ./.travis/dev_cert.pem -d
  - openssl aes-256-cbc -K $encrypted_cd0b29a82eff_key -iv $encrypted_cd0b29a82eff_iv -in ./.travis/production_cert.pem.enc -out ./.travis/production_cert.pem -d

before_install:
  - curl -fsSL https://bun.sh/install | bash
  - source ~/.bashrc
  - bun --version
  

install:
  - bun install --frozen-lockfile
  - bun x playwright install
  - bun x playwright install-deps > /dev/null

after_failure: 
  - docker logs --details ecohive-test

jobs:
  include:
    - stage: Development Tests
      if: branch != main AND type != pull_request
      script:
        - mv ./.travis/dev_cert.pem ./.travis/cert.pem
        - docker build --secret -t "ecohive-ui:$TRAVIS_BRANCH" .
        - docker run --name ecohive-test -d -p 3000:3000 ecohive-ui:$TRAVIS_BRANCH
        - docker ps
        - $SCRIPTS/wait.sh
        - docker logs --details ecohive-test
        - bun run test

    - stage: Production Tests
      if: type = pull_request
      script:
        - bun run lint
        - mv ./.travis/prod_cert.pem ./.travis/cert.pem
        - $SCRIPTS/build_image
        - docker run --name ecohive-test -d -p 3000:3000 ecohive-ui:$TRAVIS_BRANCH
        - curl http://localhost:3000/api/ping
        - docker logs ecohive-test
        - bun run test

    - stage: Deploy
      if: branch = main AND type != pull_request
      script:
        - $SCRIPTS/add_ssh_key
        - $SCRIPTS/build_image
        - $SCRIPTS/deploy_image
        - $SCRIPTS/start_container
