language: node_js

node_js:
  - 20

cache:
  npm: true # Cache npm packages to speed up builds

services: 
  - docker

before_install:
  - curl -fsSL https://bun.sh/install | bash
  - source ~/.bashrc
  - bun --version

# Install project dependencies
install:
  - bun install
  - npx playwright install


jobs:
  include:
    - stage: Local Build
      if: type = push
      name: Code Linting
      script: bun lint
      name: Code Tests
      script: bun test