language: node
node_js:
  - 20

script: 'true'

env:
  global:
    - SCRIPTS=$TRAVIS_BUILD_DIR/.travis
    - WEB_TIMEOUT=360

services:
  - docker

before_script:
  - echo -e "Host $PRODUCTION_SERVER_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_1d0be07602a8_key -iv $encrypted_1d0be07602a8_iv -in ./.travis/travis-cert.pem.enc -out ./.travis/dev_cert.pem -d
  - openssl aes-256-cbc -K $encrypted_cd0b29a82eff_key -iv $encrypted_cd0b29a82eff_iv -in ./.travis/production_cert.pem.enc -out ./.travis/production_cert.pem -d

before_install:
  - curl -fsSL https://bun.sh/install | bash
  - source ~/.bashrc
  - bun --version
  - echo "Temporary fix whilst Travis CI is borked"
  - sudo rm /etc/apt/sources.list.d/rabbitmq.list
  - sudo apt update

install:
  - bun install
  - bun x playwright install --with-deps chromium webkit

after_failure:
  - docker logs --details ecohive-test

jobs:
  include:
    - stage: test
      script:
        - $SCRIPTS/copy_certificate
        - $SCRIPTS/build_image
        - docker run --name ecohive-test -d -p 3000:3000 ecohive-ui:$TRAVIS_BRANCH
        - docker ps
        - $SCRIPTS/wait.sh
        - docker logs --details ecohive-test
        - bun run test --retries 3

after_success:
  - $SCRIPTS/add_ssh_key
  # - $SCRIPTS/build_images
  - $SCRIPTS/deploy_image
  - $SCRIPTS/start_container
