#!/bin/bash

openssl aes-256-cbc -K $encrypted_8eea991d9794_key             \
                    -iv $encrypted_8eea991d9794_iv             \
                    -in $SCRIPTS adv-soft-dev-stack-travis.enc \
                    -out $SCRIPTS/key                          \
                    -d && echo "Decrypted SSL Key" 

chmod 600 $SCRIPTS/key

