#!/bin/bash

docker save ecohive-ui                                        \
| bzip2                                                       \
| ssh -oStrictHostKeyChecking=no                              \
      -i $SCRIPTS/key                                         \
      -oPreferredAuthentications=publickey                    \
    "$PRODUCTION_SERVER_USER"@"$PRODUCTION_SERVER_ADDRESS"    \
docker load                                                   \

ssh -oStrictHostKeyChecking=no                                \
      -i $SCRIPTS/key                                         \
      -oPreferredAuthentications=publickey                    \
    "$PRODUCTION_SERVER_USER"@"$PRODUCTION_SERVER_ADDRESS" << EOF 
echo "Stopping any old containers"
docker kill ecohive-ui
echo "Deleting old container cache"
docker container rm -f ecohive-ui
echo "Starting new container"
docker run -d --name ecohive-ui -p 3000:3000 ecohive-ui
echo "Waitng 5 seconds for server to start"
sleep 5
docker logs --details ecohive-ui
docker exec -d ecohive-ui env
EOF